cms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path


app_name = "pages"

urlpatterns = [
    path( 'accounts/', include('django.contrib.auth.urls')),
    path( 'admin/doc/', include('django.contrib.admindocs.urls')),
    path( 'admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path( '__debug__/', include( debug_toolbar.urls)),
    ]
    urlpatterns += static( settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
urlpatterns += [
    path( '', include( 'pages.urls')),
]

pages/urls.py
from django.urls import path, re_path
from django.views.static import serve

from . import views

app_name = "pages"

urlpatterns = [
    path( '', views.root, name="root"),
    path( 'search/', views.SearchView(), name='haystack_search'),
    re_path( r"^(?P<path>[-\w/]+)/$", views.page_detail, name="page"),
]

pages/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from content_editor.models import Region, create_plugin_base

from feincms3 import plugins
from feincms3_meta.models import MetaMixin
from feincms3.mixins import RedirectMixin
from feincms3.pages import AbstractPage


class Page( RedirectMixin, MetaMixin, AbstractPage):
    regions = [
        Region( key="main", title=_("Main")),
    ]
    
    class Meta:
        ordering = ("position",)
        verbose_name = _("page")
        verbose_name_plural = _("pages")

PagePlugin = create_plugin_base( Page)


class RichText( plugins.richtext.RichText, PagePlugin):
    pass


class Image( plugins.image.Image, PagePlugin):
    caption = models.CharField( _("caption"), max_length=200, blank=True)
    css_class = models.CharField( _("CSS class"), max_length=5, default="left", 
        choices=( ("left",  _('Left')),
                  ("right", _('Right'))))

pages/views.py
from django.http import JsonResponse, Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy

from feincms3_meta.utils import meta_tags
from feincms3.regions import Regions

from haystack.views import SearchView as HaystackSearchView

from .models import *
from .renderers import html_renderer, json_renderer


class JSONRegions( Regions):

    def render(self, region, context=None):
        return [
            dict(
                self.renderer.render_plugin_in_context(plugin),
                type=plugin.__class__.__name__,
            )
            for plugin in self.contents[region]
        ]


def root( request):
    "Redirect to first page"
    
    page = Page.objects.active().first()
    if page is None:
        raise Http404( 'No page available')
    return redirect( page.get_absolute_url())

        
def page_detail( request, path):
    "Send a apge either as HTML or JSON"

    # Handle redirects
    page = get_object_or_404( Page, path="/%s/" % path, is_active=True)
    if page.redirect_to_url or page.redirect_to_page:
        return redirect( page.redirect_to_url or page.redirect_to_page)

    # Handle JSON
    if request.is_ajax():
        return JsonResponse({
            "id": page.pk,
            "title": page.title,
            "content": JSONRegions.from_item(
                page, renderer=json_renderer).render( "main"),
        })

    # Prepare context vars
    ancestors = list( page.ancestors().reverse())
    links = page.children.active() or (
        page.parent.children.active() if page.parent_id else [])
        
    # Render HTML
    return render( request, "pages/page.html", {
        "page": page,
        "regions": Regions.from_item( page,
            renderer=html_renderer, inherit_from=ancestors),
        "links" : links,
        "meta_tags": meta_tags( [page] + ancestors, request=request),
    })


class SearchView( HaystackSearchView):
    "Search view with AJAX support"
    
    def __init__( self, **kwargs):
        super().__init__( **kwargs)

    def __call__( self, request):
        response = super().__call__( request)

        if request.is_ajax():
            return JsonResponse([{
                    "uri" : r.object.get_absolute_url(), 
                    "title" : r.object.title
                } for r in self.results.load_all() 
            ], safe=False)
        
        return response

cms/templates/base.html
{% load static %}
{# https://startbootstrap.com/templates/simple-sidebar/ #}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

  <title>{% block title %}CMS{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="{% static 'cms/css/base.css' %}" rel="stylesheet">
  <link href="{% static 'admin/css/fonts.css' %}" rel="stylesheet">
  {% block extra_head %}{% endblock %}
</head>

<body>

  {% block body %}{% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>
</html>

pages/templates/pages/page.html
{% extends 'base.html' %}
{% load feincms3 %}
{% load i18n %}
{% load menus %}
{% load static %}

{# https://startbootstrap.com/templates/simple-sidebar/ #}


{% block title %}{{ page.title }} • {{ block.super }}{% endblock %}

{% block extra_head %}
  {{ block.super }}
  <!-- Meta tage and OpenGraph -->
  {{ meta_tags }}

  <link href="{% static 'pages/page.css' %}" rel="stylesheet">
{% endblock %}


{% block body %}
  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">
        <a href="{% url 'pages:root' %}" title="{% trans 'Home' %}"><i class="fa fa-lg fa-home"></i></a>
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" title="{% trans 'Logout' %}"><i class="fa fa-lg fa-unlock-alt"></i></a>
        {% else %}
          <a href="{% url 'login' %}" title="{% trans 'Login' %}"><i class="fa fa-lg fa-lock"></i></a>
        {% endif %}
      </div>
      <div class="list-group list-group-flush">
        {% for child in links %}
            <a href="{{ child.get_absolute_url }}"
              {% if child == page %}
                class="list-group-item list-group-item-action bg-light current"
              {% else %}
                class="list-group-item list-group-item-action bg-light"
              {% endif %}
            >{{ child.title}}</a>
        {% endfor %}
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn" id="menu-toggle"><i class="fa fa-lg fa-bars"></i></button>
        {% url 'admin:pages_page_change' page.pk as change_url %}
        {% if change_url and user.is_staff %}
          <a class="btn" href="{{ change_url }}" title="{% trans 'Edit' %}"><i class="fa fa-lg fa-pencil-square-o"></i></a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            {% block navigation %}
              {% main_menu as menu %}
              {% for p in menu %}
                <li class="nav-item">
                  <a 
                    {% if p.id in page.tree_path %}class="active nav-link"
                    {% else %}class="nav-link"{% endif %}
                    href="{{ p.get_absolute_url }}">{{ p.title|truncatewords:3 }}</a>
                </li>
              {% endfor %}
            {% endblock %}
          </ul>
        <form id="search-form" class="form-inline my-2 my-lg-0" action="{% url 'pages:haystack_search' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="🔎" aria-label="{% trans 'Search' %}" name="q" value="{{ request.GET.q }}">
        </form>
        </div>
      </nav>

      <div class="container-fluid">
        {% block content %}
          <main>
            <h1>{{ page.title }}</h1>
    
            {% render_region regions 'main' %}
          </main>
        {% endblock %}
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
{% endblock %}

pages/templates/search/search.html
{% extends 'pages/page.html' %}

{% block title %}Search results {{ block.super }}{% endblock %}

{% block content %}
    <h1>Search results</h1>

    {% if query %}
        <ul class="fa-ul">
        {% for result in page.object_list %}
            <li>
                <span class="fa-li"><i class="fa fa-file-text-o"></i></span>
                <a href="{{ result.object.get_absolute_url }}?q={{ query }}">{{ result.object.title }}</a>
            </li>
        {% empty %}
            <p>Sorry, nothing found.</p>
        {% endfor %}
      </ul>

        {% if page.has_previous or page.has_next %}
            <div>
                {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                |
                {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
            </div>
        {% endif %}
    {% else %}
        {# Show some example queries to run, maybe query syntax, something else? #}
    {% endif %}
{% endblock %}